### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by dags-** [dags-/Plots#1]
- [x] worldedit masking - allow use of worldedit within the confines of a plot
- [x] whitelist/unwhitelist command - allow owners to manage which users can build on their plot (back-end already supports this)
- [x] biome command - allow owner to change the entire biome of their plot
- [x] copy command - allow whitelisted user to copy a plot to another plot (that they own)
- [x] generator builder command
